export const activitiesData = [
  // ==========================================
  // MATHEMATICS - GRADE 6 (UPMK)
  // ==========================================
  {
    id: "math-6-1",
    subject: "math",
    grade: 6,
    title: "3D Geometric Shapes & Nets",
    description: "Explore cubes, rectangular prisms, and pyramids in 3D AR space.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Geometry", "3D Nets", "Volume"],
    arType: "3D Model Inspection",
    ncertCode: "NCERT-UPMK-01",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Plastic 3D Nets", "Geometric Solid Models", "Folding Cutouts"],
    ncertObjective: "To visualize 2D net representations and unfold them into 3D polyhedra.",
  },
  {
    id: "math-6-2",
    subject: "math",
    grade: 6,
    title: "Perimeter & Surface Area Visualizer",
    description: "Measure virtual 3D structures using interactive AR units.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Measurement", "Surface Area"],
    arType: "Interactive Measurement",
    ncertCode: "NCERT-UPMK-02",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Grid Measuring Sheets", "Unit Cubes Kit", "Centimeter Strips"],
    ncertObjective: "To derive surface area formulas (Total Surface Area = 2(lb + bh + hl)) empirically.",
  },
  {
    id: "math-6-3",
    subject: "math",
    grade: 6,
    title: "Fractions & Decimals Visualizer Kit",
    description: "Compare circular and rectangular fraction strips in interactive 3D.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Fractions", "Decimals", "Ratios"],
    arType: "Fraction Manipulative",
    ncertCode: "NCERT-UPMK-04",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Fraction Discs Set", "Rectangular Fraction Strips", "Decimal Grid"],
    ncertObjective: "To visualize equivalent fractions (1/2 = 2/4 = 4/8) and decimal representations.",
  },
  {
    id: "math-6-4",
    subject: "math",
    grade: 6,
    title: "Integers & 3D Number Line Slider",
    description: "Perform addition and subtraction of positive and negative integers.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Integers", "Number Line"],
    arType: "3D Number Slider",
    ncertCode: "NCERT-UPMK-05",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Integer Counter Tokens", "Bidirectional Number Line Track"],
    ncertObjective: "To model addition and subtraction of directed numbers on a spatial line.",
  },

  // ==========================================
  // MATHEMATICS - GRADE 7 (UPMK)
  // ==========================================
  {
    id: "math-7-1",
    subject: "math",
    grade: 7,
    title: "3D Coordinate Geometry Lattice",
    description: "Plot and manipulate points in 3-dimensional Cartesian space.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Algebra", "Coordinates"],
    arType: "3D Plotter",
    ncertCode: "NCERT-UPMK-03",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["3D Coordinate Lattice Frame", "Position Pegs", "X-Y-Z Axes Rods"],
    ncertObjective: "To understand spatial 3D orientation (x, y, z) and distance vectors.",
  },
  {
    id: "math-7-2",
    subject: "math",
    grade: 7,
    title: "Algebraic Expressions & Tile Models",
    description: "Construct linear and quadratic expressions using 3D algebra tiles.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Algebra", "Polynomials"],
    arType: "3D Tile Builder",
    ncertCode: "NCERT-UPMK-06",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Algebraic Tiles Set (x², x, 1)", "Positive/Negative Color Blocks"],
    ncertObjective: "To model expansion (x + a)(x + b) using spatial area tiles.",
  },
  {
    id: "math-7-3",
    subject: "math",
    grade: 7,
    title: "Triangle Properties & Angle Sum Proof",
    description: "Demonstrate that the interior angles of any triangle sum to 180°.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Geometry", "Triangles", "Angles"],
    arType: "Interactive Protractor",
    ncertCode: "NCERT-UPMK-07",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Cut-out Triangle Plates", "Circular Protractor Base"],
    ncertObjective: "To empirically prove Angle Sum Property (∠A + ∠B + ∠C = 180°).",
  },
  {
    id: "math-7-4",
    subject: "math",
    grade: 7,
    title: "Congruence of Triangles 3D Kit",
    description: "Test SSS, SAS, ASA, and RHS congruence criteria in 3D AR space.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Geometry", "Congruence"],
    arType: "3D Overlay Tester",
    ncertCode: "NCERT-UPMK-08",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Superimposable Acrylic Triangles", "Angle Arms"],
    ncertObjective: "To verify congruence criteria through physical superposition.",
  },

  // ==========================================
  // MATHEMATICS - GRADE 8 (UPMK & SMK)
  // ==========================================
  {
    id: "math-8-1",
    subject: "math",
    grade: 8,
    title: "Pythagorean Theorem 3D Proof",
    description: "Visualize right-angled triangles and 3D square volumes in AR.",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Pythagoras", "Geometry"],
    arType: "3D Proof Visualizer",
    ncertCode: "NCERT-SMK-01",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Right Triangle Base Plate", "Square Acrylic Blocks (a², b², c²)"],
    ncertObjective: "To verify that the area of hypotenuse square c² equals a² + b² in 3D.",
  },
  {
    id: "math-8-2",
    subject: "math",
    grade: 8,
    title: "Volume of Prisms, Cylinders & Pyramids",
    description: "Fill 3D hollow solids to prove V(Cylinder) = 3 × V(Cone).",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Volume", "Mensuration"],
    arType: "Liquid Fill Simulation",
    ncertCode: "NCERT-UPMK-09",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Hollow Cylinder & Cone Set", "Hollow Prism & Pyramid"],
    ncertObjective: "To establish volume ratio between prisms/cylinders and pyramids/cones.",
  },
  {
    id: "math-8-3",
    subject: "math",
    grade: 8,
    title: "Euler's Formula for 3D Polyhedra",
    description: "Count Vertices (V), Edges (E), and Faces (F) to verify V - E + F = 2.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Geometry", "Euler's Formula"],
    arType: "Polyhedra Counter",
    ncertCode: "NCERT-UPMK-10",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Platonic Solid Models (Cube, Octahedron, Dodecahedron)"],
    ncertObjective: "To prove Euler's relation V - E + F = 2 for all regular 3D polyhedra.",
  },
  {
    id: "math-8-4",
    subject: "math",
    grade: 8,
    title: "Linear Equations & 3D Balance Scale",
    description: "Solve linear equations with one variable using a 3D pan balance.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Algebra", "Equations"],
    arType: "Interactive Balance",
    ncertCode: "NCERT-UPMK-11",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["3D Equal Arm Balance", "Variable Weights (x)", "Unit Gram Cubes"],
    ncertObjective: "To balance pan weights to isolate and solve for variable x.",
  },

  // ==========================================
  // MATHEMATICS - GRADE 9 (SMK)
  // ==========================================
  {
    id: "math-9-1",
    subject: "math",
    grade: 9,
    title: "Trigonometric 3D Triangle Solver",
    description: "Manipulate angles and sides of 3D triangles in real-time AR.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Trigonometry", "Angles"],
    arType: "Dynamic Geometry",
    ncertCode: "NCERT-SMK-02",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Circular Protractor Plate", "Adjustable Angle Arms", "Trig Ratio Chart"],
    ncertObjective: "To measure sine, cosine, and tangent ratios on a 3D spatial triangle.",
  },
  {
    id: "math-9-2",
    subject: "math",
    grade: 9,
    title: "Surface Area & Volume of Spheres and Cones",
    description: "Derive hemisphere and spherical surface area formulas.",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Mensuration", "Spheres"],
    arType: "3D Slicer",
    ncertCode: "NCERT-SMK-04",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Sectional Hemisphere", "Cone & Cylinder Set", "Volume Cup"],
    ncertObjective: "To demonstrate Surface Area = 4πr² and Volume = (4/3)πr³.",
  },
  {
    id: "math-9-3",
    subject: "math",
    grade: 9,
    title: "Circles, Chords & Sector Angles",
    description: "Verify that angle subtended by an arc at center is double the angle at circumference.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Circles", "Chords", "Angles"],
    arType: "Interactive Circle",
    ncertCode: "NCERT-SMK-05",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Circle Board with Pins", "Elastic Angle Cord", "Degree Circular Grid"],
    ncertObjective: "To prove Center Angle Theorem (∠AOB = 2 × ∠ACB).",
  },
  {
    id: "math-9-4",
    subject: "math",
    grade: 9,
    title: "Polynomial Identity Area Proofs",
    description: "Demonstrate (a+b+c)² = a² + b² + c² + 2ab + 2bc + 2ca using 3D blocks.",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Algebra", "Polynomial Identities"],
    arType: "3D Block Puzzle",
    ncertCode: "NCERT-SMK-06",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Acrylic Volume Cubes (a³, b³, c³)", "Prism Blocks (ab, bc, ca)"],
    ncertObjective: "To assemble 3D wooden/acrylic blocks into a combined expansion cube.",
  },

  // ==========================================
  // MATHEMATICS - GRADE 10 (SMK)
  // ==========================================
  {
    id: "math-10-1",
    subject: "math",
    grade: 10,
    title: "3D Conic Sections Visualizer",
    description: "Slice cones to generate circles, ellipses, parabolas, and hyperbolas.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Conics", "Calculus Prep"],
    arType: "Interactive Slicer",
    ncertCode: "NCERT-SMK-03",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Double Cone Model", "Acrylic Cutting Plane Sheets"],
    ncertObjective: "To demonstrate conic section curves created by intersecting cutting planes.",
  },
  {
    id: "math-10-2",
    subject: "math",
    grade: 10,
    title: "Heights & Distances 3D Trigonometry",
    description: "Measure heights of buildings and towers using Clinometer and AR elevation angles.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Trigonometry", "Clinometer"],
    arType: "AR Clinometer",
    ncertCode: "NCERT-SMK-07",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Clinometer Model", "Measuring Tape", "Sight Tube Assembly"],
    ncertObjective: "To calculate height h = d × tan(θ) using angle of elevation.",
  },
  {
    id: "math-10-3",
    subject: "math",
    grade: 10,
    title: "Frustum of a Cone Surface & Volume",
    description: "Calculate curved surface area and volume of a truncated cone.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Mensuration", "Frustum"],
    arType: "3D Frustum Inspector",
    ncertCode: "NCERT-SMK-08",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Dissectible Frustum Model", "Upper Cone Cap", "Volume Measuring Cylinder"],
    ncertObjective: "To establish Frustum Volume V = (1/3)πh(r₁² + r₂² + r₁r₂).",
  },
  {
    id: "math-10-4",
    subject: "math",
    grade: 10,
    title: "Probability & 3D Sample Space Spinner",
    description: "Simulate die rolls, coin tosses, and deck draws in 3D AR space.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Probability", "Statistics"],
    arType: "3D Probability Simulator",
    ncertCode: "NCERT-SMK-09",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["3D Polyhedral Dice Set", "Sample Space Cards", "Probability Spinner"],
    ncertObjective: "To verify experimental vs theoretical probability P(E) = n(E)/n(S).",
  },

  // ==========================================
  // SCIENCE - GRADE 6 (UPSK)
  // ==========================================
  {
    id: "sci-6-1",
    subject: "science",
    grade: 6,
    title: "Interactive Solar System AR",
    description: "Explore 3D planet orbits, size scales, and axial rotations in your room.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Astronomy", "Planets", "Orbits"],
    arType: "3D Solar System",
    ncertCode: "NCERT-UPSK-01",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Celestial Sphere Globe", "Orbital Wire Racks", "Illuminated Sun Light"],
    ncertObjective: "To demonstrate revolutionary orbits, axial tilts, and planetary scales.",
  },
  {
    id: "sci-6-2",
    subject: "science",
    grade: 6,
    title: "Plant Cell Structure Explorer",
    description: "Dissect a microscopic plant cell to inspect chloroplasts and cell walls.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Biology", "Cells"],
    arType: "3D Cell Anatomy",
    ncertCode: "NCERT-UPSK-02",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Compound Microscope Kit", "Prepared Stained Onion Slides"],
    ncertObjective: "To identify cell wall, vacuole, nucleus, and chloroplast organelles.",
  },
  {
    id: "sci-6-3",
    subject: "science",
    grade: 6,
    title: "Electric Circuit & Switch Board",
    description: "Assemble series and parallel electrical circuits with bulb & battery in 3D.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Electricity", "Circuits"],
    arType: "3D Circuit Board",
    ncertCode: "NCERT-UPSK-04",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Battery Holder", "Miniature Bulbs", "Connecting Wires", "Key Switch"],
    ncertObjective: "To construct closed electrical circuits and identify conductors vs insulators.",
  },
  {
    id: "sci-6-4",
    subject: "science",
    grade: 6,
    title: "Separation of Substances & Filtration",
    description: "Simulate decantation, filtration, and evaporation of mixtures.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Chemistry", "Separation"],
    arType: "Lab Filtration Rig",
    ncertCode: "NCERT-UPSK-05",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Glass Funnel", "Filter Paper Cone", "Beaker Set", "Spirit Lamp"],
    ncertObjective: "To demonstrate insoluble solid separation using filter paper matrix.",
  },

  // ==========================================
  // SCIENCE - GRADE 7 (UPSK)
  // ==========================================
  {
    id: "sci-7-1",
    subject: "science",
    grade: 7,
    title: "Human Heart 3D Circulation",
    description: "Observe blood pumping through 3D chambers with real-time audio sync.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Anatomy", "Circulatory System"],
    arType: "Animated Anatomy",
    ncertCode: "NCERT-UPSK-03",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["3D Dissectible Heart Model", "Stethoscope Kit", "Circulation Chart"],
    ncertObjective: "To trace oxygenated and deoxygenated blood flow through heart valves.",
  },
  {
    id: "sci-7-2",
    subject: "science",
    grade: 7,
    title: "Heat Transfer & Thermal Conduction",
    description: "Visualize conduction in metal rods, convection in liquids, and thermal radiation.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Physics", "Heat Transfer"],
    arType: "Thermal Camera AR",
    ncertCode: "NCERT-UPSK-06",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Conductivity Metal Rod Stand", "Wax Nails", "Convection Flask"],
    ncertObjective: "To demonstrate differential heat conduction rates in Copper vs Iron vs Aluminum.",
  },
  {
    id: "sci-7-3",
    subject: "science",
    grade: 7,
    title: "Acids, Bases & pH Indicator Color Scale",
    description: "Test household liquids using Litmus paper, Phenolphthalein, and Turmeric in 3D.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Chemistry", "Acids & Bases"],
    arType: "3D pH Lab",
    ncertCode: "NCERT-UPSK-07",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Test Tubes & Rack", "Blue/Red Litmus Strips", "Universal Indicator Chart"],
    ncertObjective: "To classify substances as acidic (pH < 7), neutral (7), or basic (pH > 7).",
  },
  {
    id: "sci-7-4",
    subject: "science",
    grade: 7,
    title: "Light Reflection in Plane Mirrors",
    description: "Measure angle of incidence = angle of reflection using 3D laser beams.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Physics", "Light", "Reflection"],
    arType: "Laser Reflection Bench",
    ncertCode: "NCERT-UPSK-08",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Plane Mirror Holder", "Ray Streak Board", "Degree Protractor"],
    ncertObjective: "To verify Laws of Reflection (∠i = ∠r and normal lies in same plane).",
  },

  // ==========================================
  // SCIENCE - GRADE 8 (UPSK & SSK)
  // ==========================================
  {
    id: "sci-8-1",
    subject: "science",
    grade: 8,
    title: "Chemical Bonding 3D Visualizer",
    description: "Construct covalent and ionic molecular structures in AR.",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Chemistry", "Molecules"],
    arType: "Molecular Builder",
    ncertCode: "NCERT-SSK-03",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Molecular Model Kit (MMK)", "Atom Spheres & Bond Pegs"],
    ncertObjective: "To build 3D ball-and-stick representations of H₂O, CO₂, and CH₄ molecules.",
  },
  {
    id: "sci-8-2",
    subject: "science",
    grade: 8,
    title: "Human Eye 3D Anatomy & Lens Focus",
    description: "Inspect cornea, iris, retina, and simulate Myopia & Hypermetropia corrections.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Anatomy", "Optics", "Human Eye"],
    arType: "3D Eye Model",
    ncertCode: "NCERT-UPSK-09",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["3D Eye Anatomy Model", "Corrective Concave/Convex Lenses"],
    ncertObjective: "To explain focal accommodation and spectacle lens corrections.",
  },
  {
    id: "sci-8-3",
    subject: "science",
    grade: 8,
    title: "Force, Pressure & Hydraulic Lift",
    description: "Demonstrate Pascal's Law using interconnected 3D liquid syringes.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Physics", "Force", "Pressure"],
    arType: "Hydraulic Simulator",
    ncertCode: "NCERT-UPSK-10",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Hydraulic Syringe Press", "Flexible Tubing", "Weight Load Stage"],
    ncertObjective: "To prove pressure transmission P = F/A in confined fluid systems.",
  },
  {
    id: "sci-8-4",
    subject: "science",
    grade: 8,
    title: "Friction & Surface Texture Visualizer",
    description: "Measure static vs sliding friction on smooth glass, wood, and sandpaper surfaces.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Physics", "Friction"],
    arType: "3D Friction Bench",
    ncertCode: "NCERT-UPSK-11",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Spring Balance", "Wooden Block", "Rough/Smooth Track Strips"],
    ncertObjective: "To quantify frictional force dependence on surface roughness.",
  },

  // ==========================================
  // SCIENCE - GRADE 9 (SSK)
  // ==========================================
  {
    id: "sci-9-1",
    subject: "science",
    grade: 9,
    title: "Bohr Atomic Structure AR",
    description: "Inspect electron shells, protons, and neutrons in 3D atomic orbits.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Physics", "Atomic Structure"],
    arType: "3D Orbit Simulation",
    ncertCode: "NCERT-SSK-01",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Atomic Structure Model Kit", "Subatomic Particles Set"],
    ncertObjective: "To arrange electrons in K, L, M shells following 2n² electron configuration rules.",
  },
  {
    id: "sci-9-2",
    subject: "science",
    grade: 9,
    title: "Gravitation & Planetary Mass Orbits",
    description: "Simulate Kepler's Laws and gravitational attraction F = G(m₁m₂)/r².",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Physics", "Gravitation"],
    arType: "Gravity Well Simulator",
    ncertCode: "NCERT-SSK-04",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Spandex Gravity Well Frame", "Central Mass Spheres"],
    ncertObjective: "To model inverse-square law curvature of spacetime in 3D.",
  },
  {
    id: "sci-9-3",
    subject: "science",
    grade: 9,
    title: "Animal Cell vs Plant Cell Organelles",
    description: "Compare mitochondria, endoplasmic reticulum, Golgi body, and centrioles.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Biology", "Cell Organelles"],
    arType: "Dual Cell Dissector",
    ncertCode: "NCERT-SSK-05",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["3D Animal Cell Model", "3D Plant Cell Model", "Organelle Label Tags"],
    ncertObjective: "To contrast eukaryotic plant and animal cell ultra-structures.",
  },
  {
    id: "sci-9-4",
    subject: "science",
    grade: 9,
    title: "Laws of Motion & Momentum Collision",
    description: "Demonstrate Newton's 1st, 2nd, and 3rd laws using elastic steel ball collisions.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Physics", "Newton's Laws"],
    arType: "3D Collision Track",
    ncertCode: "NCERT-SSK-06",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Newton's Cradle", "Collision Track", "Photo-gate Timers"],
    ncertObjective: "To verify conservation of linear momentum p = mv.",
  },

  // ==========================================
  // SCIENCE - GRADE 10 (SSK)
  // ==========================================
  {
    id: "sci-10-1",
    subject: "science",
    grade: 10,
    title: "Optics & Light Refraction Prism",
    description: "Pass light beams through 3D lenses and prisms to analyze refraction.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Physics", "Optics", "Refraction"],
    arType: "Light Beam Simulation",
    ncertCode: "NCERT-SSK-02",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Optical Bench Kit", "Glass Prism", "Convex/Concave Lenses"],
    ncertObjective: "To measure angles of incidence, refraction, and spectrum dispersion.",
  },
  {
    id: "sci-10-2",
    subject: "science",
    grade: 10,
    title: "Human Digestive & Excretory Anatomy",
    description: "Trace food digestion through stomach, intestine, liver, and kidney nephrons in 3D.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Anatomy", "Digestive System", "Kidneys"],
    arType: "3D Organ System",
    ncertCode: "NCERT-SSK-07",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Dissectible Torso Model", "Filter Nephron Unit"],
    ncertObjective: "To map peristalsis, enzyme secretion, and urine filtration.",
  },
  {
    id: "sci-10-3",
    subject: "science",
    grade: 10,
    title: "Magnetic Field & Solenoid Field Lines",
    description: "Visualize 3D magnetic flux lines around bar magnets and current-carrying solenoids.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Physics", "Magnetism", "Solenoid"],
    arType: "3D Magnetic Lines",
    ncertCode: "NCERT-SSK-08",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Bar Magnets Set", "Iron Filings Box", "3D Compass Array", "Solenoid Coil"],
    ncertObjective: "To plot 3D magnetic lines of force and Right Hand Thumb Rule.",
  },
  {
    id: "sci-10-4",
    subject: "science",
    grade: 10,
    title: "Carbon Compounds & Hydrocarbon Chains",
    description: "Build alkanes, alkenes, alkynes, and functional group isomers in 3D.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Chemistry", "Organic Carbon"],
    arType: "Hydrocarbon Builder",
    ncertCode: "NCERT-SSK-09",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Tetrahedral Carbon Model Kit", "Double/Triple Bond Springs"],
    ncertObjective: "To construct tetrahedral sp³ carbon hybridization and structural isomers.",
  },
];

export function getActivitiesBySubjectAndGrade(subject, grade) {
  if (!subject) return [];
  return activitiesData.filter((item) => {
    const matchSubject = item.subject === subject;
    const matchGrade = grade ? item.grade === Number(grade) : true;
    return matchSubject && matchGrade;
  });
}
