export const activitiesData = [
  // Mathematics Grade 6
  {
    id: "math-6-1",
    subject: "math",
    grade: 6,
    title: "3D Geometric Shapes & Nets",
    description: "Explore cubes, rectangular prisms, and pyramids in 3D AR space.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Geometry", "3D Nets", "Volume"],
    arType: "3D Model Inspection",
    ncertCode: "NCERT-UPMK-01",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Plastic 3D Nets", "Geometric Solid Models", "Folding Cutouts"],
    ncertObjective: "To visualize 2D net representations and unfold them into 3D polyhedra.",
  },
  {
    id: "math-6-2",
    subject: "math",
    grade: 6,
    title: "Perimeter & Surface Area Visualizer",
    description: "Measure virtual 3D structures using interactive AR units.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Measurement", "Surface Area"],
    arType: "Interactive Measurement",
    ncertCode: "NCERT-UPMK-02",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["Grid Measuring Sheets", "Unit Cubes Kit", "Centimeter Strips"],
    ncertObjective: "To derive surface area formulas (Total Surface Area = 2(lb + bh + hl)) empirically.",
  },

  // Mathematics Grade 7 & 8
  {
    id: "math-7-1",
    subject: "math",
    grade: 7,
    title: "3D Coordinate Geometry",
    description: "Plot and manipulate points in 3-dimensional Cartesian space.",
    duration: "20 mins",
    difficulty: "Medium",
    topics: ["Algebra", "Coordinates"],
    arType: "3D Plotter",
    ncertCode: "NCERT-UPMK-03",
    ncertKitName: "Upper Primary Mathematics Kit (UPMK)",
    ncertApparatus: ["3D Coordinate Lattice Frame", "Position Pegs", "X-Y-Z Axes Rods"],
    ncertObjective: "To understand spatial 3D orientation (x, y, z) and distance vectors.",
  },
  {
    id: "math-8-1",
    subject: "math",
    grade: 8,
    title: "Pythagorean Theorem 3D Proof",
    description: "Visualize right-angled triangles and 3D square volumes in AR.",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Pythagoras", "Geometry"],
    arType: "3D Proof Visualizer",
    ncertCode: "NCERT-SMK-01",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Right Triangle Base Plate", "Square Acrylic Blocks (a², b², c²)"],
    ncertObjective: "To verify that the area of hypotenuse square c² equals a² + b² in 3D.",
  },

  // Mathematics Grade 9 & 10
  {
    id: "math-9-1",
    subject: "math",
    grade: 9,
    title: "Trigonometric 3D Triangle Solver",
    description: "Manipulate angles and sides of 3D triangles in real-time AR.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Trigonometry", "Angles"],
    arType: "Dynamic Geometry",
    ncertCode: "NCERT-SMK-02",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Circular Protractor Plate", "Adjustable Angle Arms", "Trig Ratio Chart"],
    ncertObjective: "To measure sine, cosine, and tangent ratios on a 3D spatial triangle.",
  },
  {
    id: "math-10-1",
    subject: "math",
    grade: 10,
    title: "3D Conic Sections Visualizer",
    description: "Slice cones to generate circles, ellipses, parabolas, and hyperbolas.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Conics", "Calculus Prep"],
    arType: "Interactive Slicer",
    ncertCode: "NCERT-SMK-03",
    ncertKitName: "Secondary Mathematics Kit (SMK)",
    ncertApparatus: ["Double Cone Model", "Acrylic Cutting Plane Sheets"],
    ncertObjective: "To demonstrate conic section curves created by intersecting cutting planes.",
  },

  // Science Grade 6
  {
    id: "sci-6-1",
    subject: "science",
    grade: 6,
    title: "Interactive Solar System AR",
    description: "Explore 3D planet orbits, size scales, and axial rotations in your room.",
    duration: "20 mins",
    difficulty: "Easy",
    topics: ["Astronomy", "Planets", "Orbits"],
    arType: "3D Solar System",
    ncertCode: "NCERT-UPSK-01",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Celestial Sphere Globe", "Orbital Wire Racks", "Illuminated Sun Light"],
    ncertObjective: "To demonstrate revolutionary orbits, axial tilts, and planetary scales.",
  },
  {
    id: "sci-6-2",
    subject: "science",
    grade: 6,
    title: "Plant Cell Structure Explorer",
    description: "Dissect a microscopic plant cell to inspect chloroplasts and cell walls.",
    duration: "15 mins",
    difficulty: "Easy",
    topics: ["Biology", "Cells"],
    arType: "3D Cell Anatomy",
    ncertCode: "NCERT-UPSK-02",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["Compound Microscope Kit", "Prepared Stained Onion Slides"],
    ncertObjective: "To identify cell wall, vacuole, nucleus, and chloroplast organelles.",
  },

  // Science Grade 7 & 8
  {
    id: "sci-7-1",
    subject: "science",
    grade: 7,
    title: "Human Heart 3D Circulation",
    description: "Observe blood pumping through 3D chambers with real-time audio sync.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Anatomy", "Circulatory System"],
    arType: "Animated Anatomy",
    ncertCode: "NCERT-UPSK-03",
    ncertKitName: "Upper Primary Science Kit (UPSK)",
    ncertApparatus: ["3D Dissectible Heart Model", "Stethoscope Kit", "Circulation Chart"],
    ncertObjective: "To trace oxygenated and deoxygenated blood flow through heart valves.",
  },
  {
    id: "sci-8-1",
    subject: "science",
    grade: 8,
    title: "Chemical Bonding 3D Visualizer",
    description: "Construct covalent and ionic molecular structures in AR.",
    duration: "25 mins",
    difficulty: "Hard",
    topics: ["Chemistry", "Molecules"],
    arType: "Molecular Builder",
    ncertCode: "NCERT-SSK-03",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Molecular Model Kit (MMK)", "Atom Spheres & Bond Pegs"],
    ncertObjective: "To build 3D ball-and-stick representations of H₂O, CO₂, and CH₄ molecules.",
  },

  // Science Grade 9 & 10
  {
    id: "sci-9-1",
    subject: "science",
    grade: 9,
    title: "Bohr Atomic Structure AR",
    description: "Inspect electron shells, protons, and neutrons in 3D atomic orbits.",
    duration: "25 mins",
    difficulty: "Medium",
    topics: ["Physics", "Atomic Structure"],
    arType: "3D Orbit Simulation",
    ncertCode: "NCERT-SSK-01",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Atomic Structure Model Kit", "Subatomic Particles Set"],
    ncertObjective: "To arrange electrons in K, L, M shells following 2n² electron configuration rules.",
  },
  {
    id: "sci-10-1",
    subject: "science",
    grade: 10,
    title: "Optics & Light Refraction Prism",
    description: "Pass light beams through 3D lenses and prisms to analyze refraction.",
    duration: "30 mins",
    difficulty: "Hard",
    topics: ["Physics", "Optics", "Refraction"],
    arType: "Light Beam Simulation",
    ncertCode: "NCERT-SSK-02",
    ncertKitName: "Secondary Science Kit (SSK)",
    ncertApparatus: ["Optical Bench Kit", "Glass Prism", "Convex/Concave Lenses"],
    ncertObjective: "To measure angles of incidence, refraction, and spectrum dispersion.",
  },
];

export function getActivitiesBySubjectAndGrade(subject, grade) {
  if (!subject) return [];
  return activitiesData.filter((item) => {
    const matchSubject = item.subject === subject;
    const matchGrade = grade ? item.grade === Number(grade) : true;
    return matchSubject && matchGrade;
  });
}
